# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import imgs

class Ui_MainWindow(object):
    def table_window(self,data):

        from table import  Ui_MainWindow
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()

        self.ui.setupUi(self.window,data)
        self.window.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(727, 547)
        MainWindow.setMinimumSize(QtCore.QSize(727, 547))
        MainWindow.setMaximumSize(QtCore.QSize(727, 547))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 731, 551))
        self.frame.setStyleSheet("background-color:#0a1931;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(190, 20, 211, 31))
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.go_btn = QtWidgets.QPushButton(self.frame)
        self.go_btn.setGeometry(QtCore.QRect(430, 30, 81, 26))
        self.go_btn.setStyleSheet("#go_btn{\n"
"background-color: rgb(219,68,55) ;\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    font: 14pt \".AppleSystemUIFont\";\n"
"border-radius:7px;\n"
"}\n"
"#go_btn:hover{\n"
"background-color:#ffc947;\n"
"\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.go_btn.setObjectName("go_btn")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame)
        self.stackedWidget.setGeometry(QtCore.QRect(40, 100, 651, 411))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.frame_6 = QtWidgets.QFrame(self.page)
        self.frame_6.setGeometry(QtCore.QRect(350, 10, 201, 361))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.scifi_btn_2 = QtWidgets.QPushButton(self.frame_6)
        self.scifi_btn_2.setGeometry(QtCore.QRect(20, 310, 171, 26))
        self.scifi_btn_2.setStyleSheet("#scifi_btn_2{\n"
"background-color: rgb(219,68,55) ;\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    font: 14pt \".AppleSystemUIFont\";\n"
"border-radius:7px;\n"
"}\n"
"#scifi_btn_2:hover{\n"
"background-color:#ffc947;\n"
"\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.scifi_btn_2.setObjectName("scifi_btn_2")
        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        self.frame_7.setGeometry(QtCore.QRect(10, 10, 191, 291))
        self.frame_7.setStyleSheet("background-image: url(:/newPrefix/images/strangerthings.png);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.frame_8 = QtWidgets.QFrame(self.page)
        self.frame_8.setGeometry(QtCore.QRect(50, 10, 201, 361))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.action_btn_2 = QtWidgets.QPushButton(self.frame_8)
        self.action_btn_2.setGeometry(QtCore.QRect(20, 310, 171, 26))
        self.action_btn_2.setStyleSheet("#action_btn_2{\n"
"background-color: rgb(219,68,55) ;\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    font: 14pt \".AppleSystemUIFont\";\n"
"border-radius:7px;\n"
"}\n"
"#action_btn_2:hover{\n"
"background-color:#ffc947;\n"
"\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.action_btn_2.setObjectName("action_btn_2")
        self.frame_9 = QtWidgets.QFrame(self.frame_8)
        self.frame_9.setGeometry(QtCore.QRect(10, 10, 191, 291))
        self.frame_9.setStyleSheet("background-image: url(:/newPrefix/images/thehundred.png);")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.frame_2 = QtWidgets.QFrame(self.page_2)
        self.frame_2.setGeometry(QtCore.QRect(50, 10, 201, 361))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.action_btn = QtWidgets.QPushButton(self.frame_2)
        self.action_btn.setGeometry(QtCore.QRect(20, 310, 171, 26))
        self.action_btn.setStyleSheet("#action_btn{\n"
"background-color: rgb(219,68,55) ;\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    font: 14pt \".AppleSystemUIFont\";\n"
"border-radius:7px;\n"
"}\n"
"#action_btn:hover{\n"
"background-color:#ffc947;\n"
"\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.action_btn.setObjectName("action_btn")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(10, 10, 191, 291))
        self.frame_3.setStyleSheet("background-image: url(:/newPrefix/images/falcon.png);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_4 = QtWidgets.QFrame(self.page_2)
        self.frame_4.setGeometry(QtCore.QRect(350, 10, 201, 361))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.scifi_btn = QtWidgets.QPushButton(self.frame_4)
        self.scifi_btn.setGeometry(QtCore.QRect(20, 310, 171, 26))
        self.scifi_btn.setStyleSheet("#scifi_btn{\n"
"background-color: rgb(219,68,55) ;\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    font: 14pt \".AppleSystemUIFont\";\n"
"border-radius:7px;\n"
"}\n"
"#scifi_btn:hover{\n"
"background-color:#ffc947;\n"
"\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.scifi_btn.setObjectName("scifi_btn")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setGeometry(QtCore.QRect(10, 10, 191, 291))
        self.frame_5.setStyleSheet("background-image: url(:/newPrefix/images/loki.png);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.stackedWidget.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        #Button Connections
        self.go_btn.clicked.connect(self.change_page)

        from TvshowsData import get_Netflix_action_data,get_Disney_action_data,get_Netflix_scifi_data,get_Disney_scifi_data
        self.action_btn.clicked.connect(lambda:self.table_window(get_Disney_action_data()))
        self.action_btn_2.clicked.connect(lambda:self.table_window(get_Netflix_action_data()))

        self.scifi_btn.clicked.connect(lambda:self.table_window(get_Disney_scifi_data()))
        self.scifi_btn_2.clicked.connect(lambda:self.table_window(get_Netflix_scifi_data()))
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Netflix"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Disney+"))
        self.go_btn.setText(_translate("MainWindow", "Go"))
        self.scifi_btn_2.setText(_translate("MainWindow", "Sci Fi"))
        self.action_btn_2.setText(_translate("MainWindow", "Action and Adeventure"))
        self.action_btn.setText(_translate("MainWindow", "Action and Adeventure"))
        self.scifi_btn.setText(_translate("MainWindow", "Sci Fi"))

    
             
    def change_page(self):
        current_combo = self.comboBox.currentIndex()
        print(current_combo)
        self.stackedWidget.setCurrentIndex(current_combo)




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
